### ISSUE TITLE
Corrupted file after decrypt file using simplecrypt in python

### ISSUE THREAD

**Issue by magic-coding** [andrewcooke/simple-crypt#15] opened 2016-11-14 07:22 UTC
I'm trying to **encrypt** and **decrypt** video using simplecrypt  and everthing works perfectlly but the problem is after program decrypt the video **Myvideo.mp4.enc** to **example-decrypt.mp4** the **example-decrypt.mp4** not working **"Corrupted file"**

My code:

    from simplecrypt import encrypt, decrypt

    def encrypt_file(file_name, key):
        with open(file_name, 'rb') as fo:
            plaintext = fo.read()
        enc = encrypt(key, plaintext)
        with open(file_name + ".enc", 'wb') as fo:
            fo.write(enc)

    def decrypt_file(file_name, dec_file, key):
        with open(file_name, 'rb') as fo:
            ciphertext = fo.read()
        dec = decrypt(key, ciphertext)
        with open(dec_file, 'wb') as fo:
            fo.write(dec)

    encrypt_file('Myvideo.mp4', '29B9A1C18678C68B')
    decrypt_file('Myvideo.mp4.enc', 'example-decrypt.mp4', '29B9A1C18678C68B')

How i can fix this please.

**Comment by colinstreicher** [comment] 2016-11-15 05:07
I'm not the author, but I cannot reproduce this issue. Are you sure this isn't a disk space error or something like that on your side?

What is the shasum of the file before encryption and after decryption? Do you have enough memory to hold the file?

**Comment by andrewcooke** [comment] 2016-11-17 22:33
that looks ok to me too.  i added an additional example to the source, which you can see [here](https://github.com/andrewcooke/simple-crypt/blob/master/src/simplecrypt/example-cmd.py) - it will do what you want.  if my command works on your file then the problem would probably be in your code.

**Comment by magic-coding** [comment] 2016-11-24 12:46
@andrewcooke Hi.
Thank you for your example cmd code but I still get the same error when I use your example.
I try with a different file with different size and I still can't open the file after encrypted.
Can you please give me an example about how I can encrypt PDF file with 10MB?

Waiting your reply.
Thank you.

**Comment by andrewcooke** [comment] 2016-11-24 16:56
hi, sorry for the frustration.  it turns out my `example-cmd.py` code had some bugs.  i've fixed it and added an additional file, `demo-large-file.sh` which shows how it is used.

if i run `demo-large.sh` i see the following output:
```
> ./demo-large-file.sh
-rw-r--r-- 1 andrew users 10M Nov 24 13:48 large.1
-rw-r--r-- 1 andrew users 11M Nov 24 13:48 large.2
-rw-r--r-- 1 andrew users 10M Nov 24 13:48 large.3
ba3e065c55b9dc26429b103b443ff9ef02f93eaa  large.1
eae48d5f70171626c220abbe69a09462f8417820  large.2
ba3e065c55b9dc26429b103b443ff9ef02f93eaa  large.3
Files large.1 and large.3 are identical
```

which is what we expect: we created a file with random data of size 10MB (file `large.1`) and encrypted that to create `large.2`, then **de**crypted `large.2` to get `large.3` (the `example-cmd.py` automatically detects encrypted files and decrypts them).  as you can see, `large.1` and `large.3` are identical, but `large.2` is different, because it is encrypted.

if, after all that, you still have problems then i need to know the operating system you are using, the version of python, and a simple example (like my "demo" file) which fails for you.

**Comment by andrewcooke** [comment] 2016-12-06 18:42
ping?  i'll close this soon if no followup.

**Closed** 2016-12-12 10:24 UTC
