### ISSUE TITLE
pycrypto dependency issues

### ISSUE THREAD

**Issue by fly** [andrewcooke/simple-crypt#9] opened 2015-08-07 21:07 UTC
it looks like pycrypto is hosted on not-pypi, and so there are a couple of problems.

1) the version of setuptools in ubuntu precise apparently does not support SNI:

```
error: https://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.7a1.tar.gz hostname 'ftp.dlitz.net' doesn't match either of 'www.dlitz.net', ‘dlitz.net```
```

2) `pycrypto-2.7a1.tar.gz` does not build:
```
    gcc -bundle -undefined dynamic_lookup -g -O2 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -DHAVE_CONFIG_H build/temp.macosx-10.10-x86_64-3.4/src/AES.o -o build/lib.macosx-10.10-x86_64-3.4/Crypto/Cipher/_AES.so
    building 'Crypto.Cipher._AESNI' extension
    gcc -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -O2 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -DHAVE_CONFIG_H -Isrc/ -I/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c src/AESNI.c -o build/temp.macosx-10.10-x86_64-3.4/src/AESNI.o -maes
    src/AESNI.c:51:16: error: index for __builtin_shufflevector must be a constant integer
        keygened = _mm_shuffle_epi32(keygened, shuf);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/usr/bin/../lib/clang/6.1.0/include/emmintrin.h:1290:12: note: expanded from macro '_mm_shuffle_epi32'
      (__m128i)__builtin_shufflevector((__v4si)__a, (__v4si) _mm_set1_epi32(0), \
               ^
    src/AESNI.c:51:14: error: assigning to '__m128i' (vector of 2 'long long' values) from incompatible type 'void'
        keygened = _mm_shuffle_epi32(keygened, shuf);
                 ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from src/AESNI.c:225:
    src/block_template.c:779:79: warning: comparison of constant 0 with boolean expression is always false [-Wtautological-constant-out-of-range-compare]
            if (PCT_CounterBEType == NULL || PyType_Check((PyObject *)PCT_CounterBEType) < 0 ||
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
    src/block_template.c:780:77: warning: comparison of constant 0 with boolean expression is always false [-Wtautological-constant-out-of-range-compare]
                     PCT_CounterLEType == NULL || PyType_Check((PyObject *)PCT_CounterLEType) < 0 ||
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
    src/block_template.c:781:47: warning: comparison of constant 0 with boolean expression is always false [-Wtautological-constant-out-of-range-compare]
                     abiver == NULL || PyInt_CheckExact(abiver) < 0 || PyInt_AS_LONG(abiver) != PCT_CTR_ABI_VERSION)
                                                                ^ ~
    3 warnings and 2 errors generated.
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/Users/jchen/.venvs/simplecrypt/bin/python3.4 -c "import setuptools, tokenize;__file__='/var/folders/qd/0tb2zcxn6xj09fxm8cjv3ppr0000gn/T/pip-ib3bwjnh-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/qd/0tb2zcxn6xj09fxm8cjv3ppr0000gn/T/pip-me6w9o4r-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jchen/.venvs/simplecrypt/bin/../include/site/python3.4/pycrypto" failed with error code 1 in /var/folders/qd/0tb2zcxn6xj09fxm8cjv3ppr0000gn/T/pip-ib3bwjnh-build
```

A possible solution is using `dependency_links` in `setup.py` to pin to `https://www.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.tar.gz`.

**Comment by andrewcooke** [comment] 2015-08-07 21:29
sorry, i'm confused.  if i run [setup-27-env.sh](setup-27-env.sh) or [setup-33-env.sh](setup-33-env.sh) on my linux, but not ubuntu) machine, i get pycrypto-2.6.1 installed (i just tried it).  everything just works.

so what are you doing that is different to that?  can we start from there?  because talking about SNI is getting way beyond what i understand right now.

**Comment by andrewcooke** [comment] 2015-08-07 21:37
similarly
```
virtualenv-2.7 --python=python2.7 /tmp/27
source /tmp/27/bin/activate
pip install simple-crypt
```
and
```
virtualenv-3.4 --python=python3.3 /tmp/33
source /tmp/33/bin/activate
pip install simple-crypt
```
work fine.

**Comment by andrewcooke** [comment] 2015-08-07 22:28
and just looking at the numbering, aren't you installing an alpha release?

and it IS on pypi - https://pypi.python.org/pypi/pycrypto

i'm closing this issue.  it seems like you're smoking crack.  but feel free to clarify if not!

**Closed by andrewcooke** 2015-08-07 22:28 UTC

**Comment by andrewcooke** [comment] 2015-08-07 22:32
(ok, now i'm worried that what was intended as a joke will be seen as an insult...  it really was just a joke!)
